name: flodo_task_manager
description: A new Flutter project for the Flodo Task Management assignment.
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.4.9
  http: ^1.2.0
  intl: ^0.19.0
  shared_preferences: ^2.2.2
  uuid: ^4.3.3
  flutter_staggered_animations: ^1.0.0
  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
