name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Or master, if your default branch is different

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Get dependencies
        working-directory: frontend
        run: flutter pub get

      - name: Initialize Web Platform
        working-directory: frontend
        run: flutter create . --platforms web

      - name: Build Web
        working-directory: frontend
        run: flutter build web --release --base-href "/flodo/" --no-tree-shake-icons

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./frontend/build/web
